# Generated by Django 4.1 on 2022-08-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='age',
            field=models.CharField(choices=[('10', '10'), ('20', '20'), ('40', '40'), ('50 or more', '50 or more'), ('30', '30')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='flavor',
            field=models.CharField(choices=[('woody', 'woody'), ('fresh', 'fresh'), ('oriental', 'oriental'), ('floral', 'floral')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='season',
            field=models.CharField(choices=[('summer', 'summer'), ('spring', 'spring'), ('fall', 'fall'), ('winter', 'winter')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='power',
            field=models.CharField(choices=[('good', 'good'), ('moderate', 'moderate'), ('bad', 'bad')], max_length=20, null=True),
        ),
    ]
