# Generated by Django 4.0.6 on 2022-08-10 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='age',
            field=models.CharField(choices=[('40', '40'), ('50 or more', '50 or more'), ('30', '30'), ('10', '10'), ('20', '20')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='flavor',
            field=models.CharField(choices=[('Woody', 'woody'), ('oriental', 'oriental'), ('fresh', 'fresh'), ('floral', 'floral')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='season',
            field=models.CharField(choices=[('summer', 'summer'), ('fall', 'fall'), ('spring', 'spring'), ('winter', 'winter')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='power',
            field=models.CharField(choices=[('moderate', 'moderate'), ('good', 'good'), ('bad', 'bad')], max_length=20, null=True),
        ),
    ]
