# Generated by Django 4.0.6 on 2022-08-19 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='age',
            field=models.CharField(choices=[('40', '40'), ('30', '30'), ('50 or more', '50 or more'), ('20', '20'), ('10', '10')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='flavor',
            field=models.CharField(choices=[('floral', 'floral'), ('oriental', 'oriental'), ('woody', 'woody'), ('fresh', 'fresh')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='gender',
            field=models.CharField(choices=[('woman', 'woman'), ('man', 'man')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='season',
            field=models.CharField(choices=[('winter', 'winter'), ('spring', 'spring'), ('summer', 'summer'), ('fall', 'fall')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='power',
            field=models.CharField(choices=[('bad', 'bad'), ('good', 'good'), ('moderate', 'moderate')], max_length=20, null=True),
        ),
    ]
