# Generated by Django 4.1 on 2022-08-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_perfume_age_alter_perfume_flavor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfume",
            name="age",
            field=models.CharField(
                choices=[
                    ("10", "10"),
                    ("20", "20"),
                    ("50 or more", "50 or more"),
                    ("30", "30"),
                    ("40", "40"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="flavor",
            field=models.CharField(
                choices=[
                    ("woody", "woody"),
                    ("fresh", "fresh"),
                    ("oriental", "oriental"),
                    ("floral", "floral"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="gender",
            field=models.CharField(
                choices=[("man", "man"), ("woman", "woman")], max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="season",
            field=models.CharField(
                choices=[
                    ("spring", "spring"),
                    ("summer", "summer"),
                    ("winter", "winter"),
                    ("fall", "fall"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
