# Generated by Django 4.1 on 2022-08-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_perfume_age_alter_perfume_flavor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfume",
            name="age",
            field=models.CharField(
                choices=[
                    ("20", "20"),
                    ("40", "40"),
                    ("10", "10"),
                    ("30", "30"),
                    ("50 or more", "50 or more"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="flavor",
            field=models.CharField(
                choices=[
                    ("floral", "floral"),
                    ("oriental", "oriental"),
                    ("fresh", "fresh"),
                    ("woody", "woody"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="perfume",
            name="season",
            field=models.CharField(
                choices=[
                    ("spring", "spring"),
                    ("summer", "summer"),
                    ("fall", "fall"),
                    ("winter", "winter"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="power",
            field=models.CharField(
                choices=[("moderate", "moderate"), ("bad", "bad"), ("good", "good")],
                max_length=20,
                null=True,
            ),
        ),
    ]
