# Generated by Django 4.0.6 on 2022-08-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_perfume_age_alter_perfume_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='age',
            field=models.CharField(choices=[('40', '40'), ('20', '20'), ('30', '30'), ('50 or more', '50 or more'), ('10', '10')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='season',
            field=models.CharField(choices=[('spring', 'spring'), ('winter', 'winter'), ('summer', 'summer'), ('fall', 'fall')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='power',
            field=models.CharField(choices=[('bad', 'bad'), ('moderate', 'moderate'), ('good', 'good')], max_length=20, null=True),
        ),
    ]
