# Generated by Django 4.0.6 on 2022-08-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_perfume_age_alter_perfume_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='age',
            field=models.CharField(choices=[('30', '30'), ('20', '20'), ('50 or more', '50 or more'), ('10', '10'), ('40', '40')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='flavor',
            field=models.CharField(choices=[('oriental', 'oriental'), ('floral', 'floral'), ('woody', 'woody'), ('fresh', 'fresh')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='season',
            field=models.CharField(choices=[('winter', 'winter'), ('fall', 'fall'), ('summer', 'summer'), ('spring', 'spring')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='power',
            field=models.CharField(choices=[('moderate', 'moderate'), ('bad', 'bad'), ('good', 'good')], max_length=20, null=True),
        ),
    ]
