# Generated by Django 4.1 on 2022-08-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_perfume_age_alter_perfume_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='age',
            field=models.CharField(choices=[('30', '30'), ('10', '10'), ('50 or more', '50 or more'), ('20', '20'), ('40', '40')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='flavor',
            field=models.CharField(choices=[('floral', 'floral'), ('woody', 'woody'), ('fresh', 'fresh'), ('oriental', 'oriental')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='gender',
            field=models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='season',
            field=models.CharField(choices=[('fall', 'fall'), ('spring', 'spring'), ('summer', 'summer'), ('winter', 'winter')], max_length=20, null=True),
        ),
    ]
