# Generated by Django 4.0.6 on 2022-08-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Perfumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='perfume',
            name='age',
            field=models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50 or more', '50 or more')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='explain',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='flavor',
            field=models.CharField(choices=[('fresh', 'fresh'), ('floral', 'floral'), ('woody', 'woody'), ('oriental', 'oriental')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='gender',
            field=models.CharField(choices=[('woman', 'woman'), ('man', 'man')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='season',
            field=models.CharField(choices=[('spring', 'spring'), ('summer', 'summer'), ('winter', 'winter'), ('fall', 'fall')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='situation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='notes_top',
            field=models.ManyToManyField(to='app.note'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='perfumers',
            field=models.ManyToManyField(to='app.perfumer'),
        ),
    ]
