# Generated by Django 4.0.6 on 2022-08-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_note_perfumer_perfume_age_perfume_explain_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note_middle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Note_top',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameModel(
            old_name='Note',
            new_name='Note_base',
        ),
        migrations.AddField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='perfume_images/'),
        ),
        migrations.AddField(
            model_name='perfume',
            name='notes_base',
            field=models.ManyToManyField(to='app.note_base'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='age',
            field=models.CharField(choices=[('30', '30'), ('10', '10'), ('50 or more', '50 or more'), ('40', '40'), ('20', '20')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='flavor',
            field=models.CharField(choices=[('oriental', 'oriental'), ('woody', 'woody'), ('floral', 'floral'), ('fresh', 'fresh')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='gender',
            field=models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='season',
            field=models.CharField(choices=[('summer', 'summer'), ('spring', 'spring'), ('fall', 'fall'), ('winter', 'winter')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfume',
            name='notes_middle',
            field=models.ManyToManyField(to='app.note_middle'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='notes_top',
            field=models.ManyToManyField(to='app.note_top'),
        ),
    ]
