# Generated by Django 4.0.6 on 2022-08-18 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_postmodel_user_alter_perfume_age_and_more'),
        ('app', '0005_review_rating_alter_perfume_age_alter_perfume_flavor_and_more'),
    ]

    operations = [
    ]
