# Generated by Django 4.0.6 on 2022-08-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_note_middle_note_top_rename_note_note_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='age',
            field=models.CharField(choices=[('30', '30'), ('50 or more', '50 or more'), ('40', '40'), ('20', '20'), ('10', '10')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='flavor',
            field=models.CharField(choices=[('fresh', 'fresh'), ('Woody', 'woody'), ('floral', 'floral'), ('oriental', 'oriental')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='gender',
            field=models.CharField(choices=[('woman', 'woman'), ('man', 'man')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='season',
            field=models.CharField(choices=[('summer', 'summer'), ('winter', 'winter'), ('fall', 'fall'), ('spring', 'spring')], max_length=20, null=True),
        ),
    ]
