# Generated by Django 4.0.6 on 2022-08-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_perfume_age_alter_perfume_flavor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='age',
            field=models.CharField(choices=[('50 or more', '50 or more'), ('30', '30'), ('20', '20'), ('10', '10'), ('40', '40')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='flavor',
            field=models.CharField(choices=[('Woody', 'woody'), ('floral', 'floral'), ('oriental', 'oriental'), ('fresh', 'fresh')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='season',
            field=models.CharField(choices=[('winter', 'winter'), ('spring', 'spring'), ('summer', 'summer'), ('fall', 'fall')], max_length=20, null=True),
        ),
    ]
