# Generated by Django 4.0.6 on 2022-08-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_perfume_age_alter_perfume_flavor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='first_scent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='put_scent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rest_scent',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='type_explain',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='age',
            field=models.CharField(choices=[('10', '10'), ('20', '20'), ('30', '30'), ('40', '40'), ('50 or more', '50 or more')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='flavor',
            field=models.CharField(choices=[('oriental', 'oriental'), ('Woody', 'woody'), ('floral', 'floral'), ('fresh', 'fresh')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='gender',
            field=models.CharField(choices=[('man', 'man'), ('woman', 'woman')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='season',
            field=models.CharField(choices=[('summer', 'summer'), ('winter', 'winter'), ('spring', 'spring'), ('fall', 'fall')], max_length=20, null=True),
        ),
    ]
