# Generated by Django 4.0.6 on 2022-08-10 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_review_first_scent_review_put_scent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='power',
            field=models.CharField(choices=[('good', 'good'), ('bad', 'bad'), ('moderate', 'moderate')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='age',
            field=models.CharField(choices=[('30', '30'), ('10', '10'), ('20', '20'), ('40', '40'), ('50 or more', '50 or more')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='flavor',
            field=models.CharField(choices=[('Woody', 'woody'), ('oriental', 'oriental'), ('floral', 'floral'), ('fresh', 'fresh')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='gender',
            field=models.CharField(choices=[('woman', 'woman'), ('man', 'man')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='season',
            field=models.CharField(choices=[('summer', 'summer'), ('spring', 'spring'), ('fall', 'fall'), ('winter', 'winter')], max_length=20, null=True),
        ),
    ]
