# Generated by Django 4.0.6 on 2022-07-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_perfume_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='country',
            field=models.CharField(max_length=50),
        ),
    ]
